import { gql } from 'graphql-tag';

export const STRAPI_DATA = gql`
  query {
    companyinfo {
      data {
        attributes {
          company
          street
          postalcode
          city
          phone
          email
          contact
          district
          latitude
          longitute
          web
          logo {
            data {
              attributes {
                url
                alternativeText
              }
            }
          }
          invertlogo {
            data {
              attributes {
                url
                alternativeText
              }
            }
          }
        }
      }
    }
    faqs {
      data {
        id
        attributes {
          question
          answer
        }
      }
    }
    newsarticels {
      data {
        id
        attributes {
          header
          teaser
          content
          slug
          image {
            data {
              id
              attributes {
                url
                alternativeText
              }
            }
          }
        }
      }
    }
    pages {
      data {
        id
        attributes {
          pageName
          pageLink
          header_image {
            data {
              id
              attributes {
                url
                alternativeText
              }
            }
          }
          SEO {
            pageTitle
            seoDesicription
            seoKeywords
            type
            seoImage {
              data {
                id
                attributes {
                  url
                  alternativeText
                }
              }
            }
          }
          pageSections {
            __typename
            ... on ComponentSectionsStandardSection {
              id
              sectionText
              sectionImage {
                data {
                  id
                  attributes {
                    url
                    alternativeText
                  }
                }
              }
            }
          }
        }
      }
    }
    customers {
      data {
        id
        attributes {
          company
          city
          logo {
            data {
              attributes {
                url
                alternativeText
              }
            }
          }
          invertLogo {
            data {
              attributes {
                url
                alternativeText
              }
            }
          }
          projects(sort: "launchDate:desc") {  # Projekte des Kunden hinzufügen
            data {
              id
              attributes {
                projectTitle  # Titel des Projekts
                projectImages {
                  data {
                    attributes {
                      url        # URL der Projektbilder
                      alternativeText  # Alternativer Text der Bilder
                    }
                  }
                }
                launchDate   # Startdatum des Projekts
                projectDescription  # Beschreibung des Projekts
                link
                webpage
                Technologien {
                  data {
                    attributes {
                      titel
                      icon
                    }
                  }
                }
                customer {
                  data {
                    attributes {
                      company
                      city
                      
                    }
                    id
                  }
                }
              }
            }
          }
        }
      }
    }
  }
`;
